version: '3.7'

networks:
  jaeger-test:
    driver: bridge

services:
  api:
    build: api
    networks:
      - jaeger-test
    ports:
      - '8080:8080'
    environment:
      - 'JAEGER_ENDPOINT=http://jaeger:14268/api/traces'

  jaeger:
    image: jaegertracing/all-in-one:1.14
    networks:
      - jaeger-test
    ports:
      - '14268:14268'
      - '16686:16686'
      - '5775:5775/udp'
      - '5778:5778'
      - '6831:6831/udp'
      - '6832:6832/udp'
      - '9411:9411'
